branch-defaults:
  master:
    environment: tweetworker-env
global:
  application_name: TweetStream
  default_ec2_keyname: tweetMap
  default_platform: Node.js
  default_region: us-west-2
  profile: eb-cli
  sc: git
